// <auto-generated />
using System;
using GestaoLoja3D.Dominio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoLoja3D.Dominio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.ItemEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<decimal>("QuantidadeComprada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantidadeDisponivel")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("ItemEstoque");

                    b.HasDiscriminator().HasValue("ItemEstoque");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.MaterialUtilizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeUtilizada")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MateriaisUtilizados");
                });

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TempoProducao")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.Filamento", b =>
                {
                    b.HasBaseType("GestaoLoja3D.Dominio.Models.ItemEstoque");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Filamento");
                });

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.Insumo", b =>
                {
                    b.HasBaseType("GestaoLoja3D.Dominio.Models.ItemEstoque");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnidadeDeMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Insumo");
                });

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.MaterialUtilizado", b =>
                {
                    b.HasOne("GestaoLoja3D.Dominio.Models.ItemEstoque", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoLoja3D.Dominio.Models.Produto", null)
                        .WithMany("MateriaisUtilizados")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("GestaoLoja3D.Dominio.Models.Produto", b =>
                {
                    b.Navigation("MateriaisUtilizados");
                });
#pragma warning restore 612, 618
        }
    }
}
